# Generated by Django 4.2.1 on 2023-06-09 09:16

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default='2001-01-01', validators=[users.models.validate_minimum_age]),
            preserve_default=False,
        ),
    ]
